# -*- python -*-
Import("env")

env.CheckSwig("python", ilang="c++", includedProducts="utils daf_base")
env.LoadableModuleIncomplete("_securityLib", Split("securityLib.i"),
                             LIBS=env.getlibs("boost utils daf_base security"))
