# -*- python -*-
Import("env")

env.CheckSwig("python", ilang="c++", includedProducts="utils")
env.LoadableModuleIncomplete("_securityLib", Split("securityLib.i"),
                             LIBS=env.getlibs("boost utils security pex_logging pex_exceptions daf_base"))
