# -*- python -*-
Import('env')
import os

sourceFiles = ["../src/" + fn for fn in os.listdir("../src/") if fn.endswith(".cc")]

env.SharedLibrary(
    'security',
    sourceFiles,
    LIBS=env.getlibs("boost utils daf_base pex_logging")
)
